### ISSUE TITLE
Install mysql-server-5.6+ for TestLink 1.9.15 on Debian 8

### ISSUE THREAD

**Issue by chusiang** [chusiang/testlink.ansible.role#6]
Survey 了一下得知 Debian 8 在裝 mysql-server-5.6+ 之前，需要先下載 mysql 官方的開發包才行。

```
#!/bin/bash
cd /tmp

# Confirm the version at http://dev.mysql.com/downloads/repo/apt/
wget -O mysql-apt-config.deb https://dev.mysql.com/get/mysql-apt-config_0.8.0-1_all.deb

sudo dpkg -i mysql-apt-config.deb

# At the popup-page, select "Apply"

# Install mysql-server package
sudo apt-get update
sudo apt-get install mysql-server-5.6 -y
```
- [MySQL :: A Quick Guide to Using the MySQL APT Repository](https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/)
- [Debian 8 - Install MySQL 5.6](http://blog.programster.org/debian-8-install-mysql-5-6/)

**Comment by chusiang** [comment]
已有前人解答怎麼在 geerlingguy.mysql role 時，安裝最新的 mysql-server 了，最後採用在不同 distribution 代入不同 mysql-server package name 的解法。
- https://github.com/chusiang/testlink.ansible.role/blob/develop/setup.yml#L22

然用在使用 geerlingguy.mysql role 前，先跑過新增 mysql repo 的 tasks。
- https://github.com/chusiang/testlink.ansible.role/blob/develop/tasks/add_mysql_repo.yml

Example:

```
- name: Deploy MySQL servers and databases
  hosts: db
  become: yes
  pre_tasks:
  - name: Add MySQL repository key
    apt_key: url=http://repo.mysql.com/RPM-GPG-KEY-mysql state=present

  - name: Add MySQL Server repository
    apt_repository: repo='deb http://repo.mysql.com/apt/debian/ jessie mysql-5.6' state=present

  - name: Add MySQL Python Connector repository
    apt_repository: repo='deb http://repo.mysql.com/apt/debian/ jessie connector-python-2.0' state=present

  roles:
  - geerlingguy.mysql
```
- [Ability to install the latest version MySQL · Issue #64 · geerlingguy/ansible-role-mysql](https://github.com/geerlingguy/ansible-role-mysql/issues/64)
